### ISSUE TITLE
Labkey authentication fails for v2.8.0 CIPAPI

### ISSUE THREAD

**Issue by s-boardman** [NHS-NGS/GeL2MDT#165]
This is on the `active_dirctory_support` branch.

According to @cboustred Labkey will still be available for 100k cases (including those in the test version of CIPAPI v2.8.0).

Performing `run_batch_update` without using the `--skip-demographics` flag produces the following error:

```
Encountered error: '401: Authorization Failed'
Traceback (most recent call last):
  File "/home/sboardman/Projects/GeL2MDT/gelweb/gel2mdt/database_utils/multiple_case_adder.py", line 200, in update_database
    added_cases = self.add_cases()
  File "/home/sboardman/Projects/GeL2MDT/gelweb/gel2mdt/database_utils/multiple_case_adder.py", line 436, in add_cases
    demographics = demographic_handler.get_demographics(participant_ids)
  File "/home/sboardman/Projects/GeL2MDT/gelweb/gel2mdt/database_utils/demographics_handler.py", line 28, in get_demographics
    lk.query.QueryFilter('participant_id', query, 'in')
  File "/home/sboardman/.pyenv/versions/3.7.4/envs/Gel2MDT/lib/python3.7/site-packages/labkey/query.py", line 261, in select_rows
    return server_context.make_request(url, payload, timeout=timeout)
  File "/home/sboardman/.pyenv/versions/3.7.4/envs/Gel2MDT/lib/python3.7/site-packages/labkey/utils.py", line 169, in make_request
    handle_request_exception(e, server_context=self)
  File "/home/sboardman/.pyenv/versions/3.7.4/envs/Gel2MDT/lib/python3.7/site-packages/labkey/utils.py", line 70, in handle_request_exception
    raise e
  File "/home/sboardman/.pyenv/versions/3.7.4/envs/Gel2MDT/lib/python3.7/site-packages/labkey/utils.py", line 167, in make_request
    return handle_response(raw_response)
  File "/home/sboardman/.pyenv/versions/3.7.4/envs/Gel2MDT/lib/python3.7/site-packages/labkey/utils.py", line 89, in handle_response
    raise RequestAuthorizationError(response)
labkey.exceptions.RequestAuthorizationError: '401: Authorization Failed'
```

Looks like it's trying to use the id/secret credentials or ignoring the legacy credentials I've got stored as environment variables.

**Comment by s-boardman** [comment]
It works if you've set up your .netrc properly as per the instructions. :+1:
